[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/Jeevankumar-Resume.pdf"
  to = "/Jeevankumar-Resume.pdf"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "18"
